version: "3.3"

services:
  # TODO: improve naming
  murq-worldbuilding-backend-service:
    build:
      context: .
      dockerfile: ./modules/worldbuilding.backend/Dockerfile
    image: murq-worldbuilding-backend-service-image
    container_name: murq-worldbuilding-backend-service-container
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "7701:7701"

  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - murq-worldbuilding-backend-service
    networks:
      - app-network

  # postgres:
  #   image: postgres:13.5
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

networks:
  app-network:
    driver: bridge
