name: CI2

on:
  push:
    branches: [main]

run-name: ${{ github.actor }} is running CI2 (TODO -> UT 🧪 + deployment)

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
